[project]
name = "week1"
version = "0.1.0"
description = "A module to learn basic of Python for SPL"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "numpy>=1.27.0",
]

[project.optional-dependencies]
dev = [
    "black>=24.3.0",
]
